### ISSUE TITLE
Cannot call method 'apply' of undefined

### ISSUE THREAD

**Issue by reneras** [matb33/meteor-collection-hooks#105]
Just installed the package. After this simple line `Meteor.publish("items");` i get the following error:

```javascript
TypeError: Cannot call method 'apply' of undefined
at packages/matb33:collection-hooks/collection-hooks.js:220:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at [object Object]._handler (packages/matb33:collection-hooks/collection-hooks.js:219:1)
at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
at packages/ddp/livedata_server.js:546:1
```

Seems like `func` ( https://github.com/matb33/meteor-collection-hooks/blob/master/collection-hooks.js#L218 ) is undefined. I assume because the provided collection is empty, but not sure. Going to investigate and submit PR if I find something.

**Comment by matb33** [comment]
I don't think the second argument is optional: http://docs.meteor.com/#/basic/Meteor-publish

**Comment by reneras** [comment]
I see. One would assume the whole collection with a sensible limit. Thanks.

**Comment by rhyslbw** [comment]
@reneras  Although the name of a Meteor.publish function correlates to a Collection a lot of the time, it's a first class citizen and can be used to publish documents from any data source, reactive or not. Meteor does a great job of hiding away the complexity of the DDP implementation when publishing a cursor, so it can get confusing at first.
