### ISSUE TITLE
MongoError: '$set' is empty

### ISSUE THREAD

**Issue by almogdesign** [matb33/meteor-collection-hooks#130]
I'm getting the following error and I thin it's do to the Collection Package
MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}

Log 
at Object.collection.(anonymous function) [as update] (packages/matb33:collection-hooks/collection-hooks.js:103:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/mongo/collection.js:575:1)
    at Object.mfPkg.langUpdate (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:126:1)
    at Object.mfPkg.syncAll (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:167:1)

**Comment by dr-dimitru** [comment]
+ 1

**Comment by matb33** [comment]
It's not much to go on, which is why I haven't taken a deeper look.  I'll need something else to help debug this.

**Comment by jimmiebtlr** [comment]
I'll take a shot in the dark.  Are you using collection2 + simple schema?  If so this can be caused by your insertion having the field removed before insertion.

**Comment by matb33** [comment]
If you have more to go on, you can re-open
