### ISSUE TITLE
Conflicht with aldeed:tabular?

### ISSUE THREAD

**Issue by brylie** [matb33/meteor-collection-hooks#133]
When installing this package on a project that uses aldeed:tabular, I get the following error:

```
Error: Tabular.Table options must specify collection
     at new Tabular.Table (packages/aldeed:tabular/common.js:20:1)
     at packages/yogiben:admin/lib/both/startup.coffee:100:27
     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
     at adminCreateTables (packages/yogiben:admin/lib/both/startup.coffee:77:4)
     at __coffeescriptShare (packages/yogiben:admin/lib/both/startup.coffee:178:2)
     at /home/brylie/Code/Apinf/api-umbrella-dashboard/.meteor/local/build/programs/server/boot.js:229:5
```

I am not sure where to troubleshoot this issue, e.g. with yogiben:admin or aldeed:tabular. However, removing the collection hooks package resolves the errors.

**Comment by brylie** [comment]
There is one solution posted on the [yogiben:meteor-admin #216](https://github.com/yogiben/meteor-admin/issues/216). It seems that editing the `.meteor/packages` file and moving `matb33:collection-hooks` directly below `aldeed:collection2` resolves the issue. The underlying cause is still under question.

**Comment by brylie** [comment]
I have posted an issue describing the [load order of the 'comments' and 'collection-hooks' packages in yogiben:meteor-starter](https://github.com/yogiben/meteor-starter/issues/84) that may be the underlying cause of this issue.

**Comment by matb33** [comment]
At some point I will look into all this and find a definitive solution

https://github.com/matb33/meteor-collection-hooks/issues/125#issuecomment-109015219

**Comment by StorytellerCZ** [comment]
@matb33 Do you think this is now solved?
