### ISSUE TITLE
Got an exception

### ISSUE THREAD

**Issue by hazio** [matb33/meteor-collection-hooks#194]
From log:

```
I20160812-16:49:00.969(3)? Exception in setInterval callback: MongoError: Cannot apply $pull to a non-array value
I20160812-16:49:00.970(3)?     at Object.Future.wait (/home/hakki/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20160812-16:49:00.971(3)?     at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
I20160812-16:49:00.971(3)?     at MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:771:49)
I20160812-16:49:00.972(3)?     at Object.<anonymous> (packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:403:1)
I20160812-16:49:00.972(3)?     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:111:1)
I20160812-16:49:00.973(3)?     at [object Object].update (packages/mongo/collection.js:589:29)
I20160812-16:49:00.973(3)?     at AccountsServer.Ap._expirePasswordResetTokens (packages/accounts-base/accounts_server.js:1137:14)
I20160812-16:49:00.974(3)?     at packages/accounts-base/accounts_server.js:1174:14
I20160812-16:49:00.974(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160812-16:49:00.975(3)?     at packages/meteor/timers.js:6:1
I20160812-16:49:00.975(3)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160812-16:49:00.976(3)?     - - - - -
I20160812-16:49:00.976(3)?     at Function.MongoError.create (/home/hakki/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
I20160812-16:49:00.977(3)?     at toError (/home/hakki/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:114:22)
I20160812-16:49:00.977(3)?     at Object.cb (/home/hakki/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:1015:67)
I20160812-16:49:00.978(3)?     at /home/hakki/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:443:18
I20160812-16:49:00.979(3)?     at authenticateStragglers (/home/hakki/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:399:16)
I20160812-16:49:00.979(3)?     at [object Object].messageHandler (/home/hakki/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:421:5)
I20160812-16:49:00.980(3)?     at Socket.<anonymous> (/home/hakki/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:294:22)
I20160812-16:49:00.980(3)?     at emitOne (events.js:77:13)
I20160812-16:49:00.981(3)?     at Socket.emit (events.js:169:7)
I20160812-16:49:00.981(3)?     at readableAddChunk (_stream_readable.js:153:18)
I20160812-16:49:00.982(3)?     at Socket.Readable.push (_stream_readable.js:111:10)
I20160812-16:49:00.982(3)?     at TCP.onread (net.js:536:20)
```

I wonder what caused the exception.

**Comment by galdo666** [comment]
https://github.com/meteor/meteor/pull/7534

**Comment by hazio** [comment]
thanks @galdo666
