### ISSUE TITLE
Error: First argument to new Mongo.Collection must be a string or null with meteor 1.8

### ISSUE THREAD

**Issue by monkeydri** [matb33/meteor-collection-hooks#250]
I installed meteor-collection-hooks from the repo (`cd packages`, `git clone https://github.com/matb33/meteor-collection-hooks` and `meteor add matb33:collection-hooks`) and switched to branch meteor-1.6.1 because I had the error #76.

I am now facing another issue :

```
W20190209-18:11:14.351(1)? (STDERR) Error: First argument to new Mongo.Collection must be a string or null
W20190209-18:11:14.351(1)? (STDERR)     at _0xb3b0x8.(anonymous function).Collection (packages/mongo/collection.js:36:11)
W20190209-18:11:14.352(1)? (STDERR)     at new _0xb3b0x8.(anonymous function) (packages/meteortoys_toykit.js:30:7185)
W20190209-18:11:14.352(1)? (STDERR)     at new ns.Collection (packages/matb33_collection-hooks.js:298:15)
W20190209-18:11:14.352(1)? (STDERR)     at autoupdate_server.js (packages/autoupdate/autoupdate_server.js:39:3)
W20190209-18:11:14.352(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190209-18:11:14.352(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190209-18:11:14.352(1)? (STDERR)     at require (packages/modules-runtime.js:258:21)
```

Is this project still alive ?

**Comment by StorytellerCZ** [comment]
@didrip I think this should be fixed with release 0.9. Can you check?
